#!/bin/sh
# Auto-generated by pgx. You may edit this, or delete it to have a new one created.

: ${GCC:=gcc}

if [ x"$CARGO_BIN_NAME" = x'sql-generator' ]; then
    temp="$(mktemp pgx-XXX)"
    if [ x"$(uname 2> /dev/null)" = x'Darwin' ]; then
        echo '*_pgx_internals_*' > "$temp"
        "$GCC" -exported_symbols_list "$temp" "$@"
    else
        echo '{ __pgx_internals_*; };' > "$temp"
        "$GCC" "-Wl,-dynamic-list=$temp" "$@"
    fi
    exec rm -f "$temp"
fi

exec "$GCC" -Wl,-undefined,dynamic_lookup "$@"
